name: bca_library
description: "A BCA study materials application"
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI and functionality packages
  cupertino_icons: ^1.0.8
  curved_navigation_bar: ^1.0.6
  shared_preferences: ^2.5.3
  provider: ^6.1.1
  url_launcher: ^6.2.5
  animated_text_kit: ^4.2.2
  youtube_player_flutter: ^9.0.0
  flutter_carousel_widget: ^2.1.2
  flutter_pdfview: ^1.4.0+1
  syncfusion_flutter_pdfviewer: ^29.1.41
  path_provider: ^2.1.5
  share_plus: ^7.2.2
  permission_handler: ^11.2.0
  app_settings: ^5.1.1
  device_info_plus: ^11.4.0
  path: ^1.8.3
  firebase_core: ^3.13.1
  firebase_analytics: ^11.4.6
  firebase_auth: ^5.5.4
  firebase_database: ^11.0.0
  logger: ^2.5.0
  google_sign_in: ^6.3.0
  webview_flutter: ^4.13.0
  http: ^1.2.0
  intl: ^0.19.0
  
  # Encryption dependencies
  encrypt: ^5.0.3
  crypto: ^3.0.3
  pointycastle: ^3.7.3
  asn1lib: ^1.5.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/pdfs/

  fonts:
    - family: Bauhaus 93
      fonts:
        - asset: assets/fonts/BAUHS93.ttf
        - asset: assets/fonts/Bauhaus 93 Regular.ttf

# App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/BCA1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/BCA1.png"
  min_sdk_android: 21
  remove_alpha_ios: true
