// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcckwIFOXbRTUR6e4ud9jTZDjr1RhnFaQ',
    appId: '1:567128132210:web:a886d7e5f1738b92a250eb',
    messagingSenderId: '567128132210',
    projectId: 'bcalibraryapp',
    authDomain: 'bcalibraryapp.firebaseapp.com',
    storageBucket: 'bcalibraryapp.firebasestorage.app',
    measurementId: 'G-LDV5VJBZZE',
    databaseURL:
        'https://bcalibraryapp-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcckwIFOXbRTUR6e4ud9jTZDjr1RhnFaQ',
    appId: '1:567128132210:android:a886d7e5f1738b92a250eb',
    messagingSenderId: '567128132210',
    projectId: 'bcalibraryapp',
    storageBucket: 'bcalibraryapp.firebasestorage.app',
    databaseURL:
        'https://bcalibraryapp-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );
}
